server:
  port: 8090

spring:
  application:
    name: ms-registry-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost
    # Rutas estáticas para evitar el bypass por canales alternativos
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        # MITIGACIÓN: Solo exponemos lo mínimo indispensable
        include: "health,info"
  endpoint:
    health:
      show-details: never
      # Desactivamos grupos de salud adicionales que causan la alerta en Snyk
      probes:
        enabled: false
